---
version: '3'

services:
  redis:
    image: redis:alpine
    ports:
     - 6379:6379

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.0
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTIC_PASSWORD=secret
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.0
    environment:
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=secret
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch