---
version: '3'

services:
  redis:
    image: redis:alpine
    ports:
     - 6379:6379

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
