
[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.3.0"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.0.4"

[[constraint]]
  name = "github.com/olivere/elastic"
  version = "5.0.58"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
